baseURL = 'https://dedale10D.pages.dev/'
languageCode = 'fr-fr'
title = "Dedale d'idees"
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  showReadingTime = true
  showShareButtons = true  
  fullName = "Arnaud"
  subtitle = "Journal de bord d'un curieux sous Linux"
  contentTypeName = "posts"
  dateFormat = "02 Jan 2006"
  showMenuItems = 3 
  mainSections = ["posts"]
  disableSpecial1stPost = true
  

[menu]

  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 2

  [[menu.main]]
    name = "Bidouilles"
    url = "/Bidouilles/"
    weight = 2

  [[menu.main]]
    name = "Carnet"
    url = "/Carnet/"
    weight = 2

  
  
